### ISSUE TITLE
Outgoing patch not always generated

### ISSUE THREAD

**Issue by warpech** [Starcounter/Home#100]
@chrhol please take a look. I think this is a new problem in patches generation. Sorry that I cannot give a better title to this issue, but I am not sure where it comes from exactly.

### Steps to reproduce

1. Start Launcher `develop` branch
2. Start KitchenSink `develop` branch
3. Go to `http://localhost:8080/KitchenSink`
4. Click on the Settings icon in the top right corner
5. Click on the KitchenSink link in the left menu

### Expected

You should see KitchenSink

### Actual

You see a white area instead of KitchenSink

I believe that the bug is not in an app. If you put a breakpoint at line https://github.com/StarcounterApps/Launcher/blob/779956c34cde672a836d4948d2e311eecd1899ae/src/Launcher/Helper/LauncherHelper.cs#L188, you will see that the step (5) from the above list causes `ActiveWorkspace` property to change to true. But that patch is not sent to the client in the response.

### Screenshot

![bug](https://cloud.githubusercontent.com/assets/566463/25756925/d8e08434-31c8-11e7-99f3-80db07f5adbf.gif)

**Comment by chrhol** [comment]
Yes, this looks like a bug in Starcounter. The partial viewmodel instance in Launcher for a workspace is never marked as sent to the client for some reason. This have the effect that the server later thinks specific properties does not need to be marked as dirty since the whole instance will be sent (which is incorrect).

I have not yet found a solution for this. Working on it.

**Comment by chrhol** [comment]
Found a fix, will push it soon. The cause was another "fix" made earlier, see https://github.com/Starcounter/Home/issues/97

**Comment by chrhol** [comment]
Pushed now. Will be available in the next builds.

**Comment by warpech** [comment]
I can confirm it is fixed now. Tested in 2.3.1.6433
