### ISSUE TITLE
Add DbHelper.FromId that accepts string

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Home#111]
There are tons of code like this:
```cs
DbHelper.FromID(DbHelper.Base64DecodeObjectID(userId)) as SystemUser
```

I propose adding a method for it. I would gladly keep it in some sort of external library, but we have no such thing:
```cs
/// Returns object of type T with given ID in encoded in base64
/// Throws FormatException if the id is not valid base64
/// returns null if no object is found or if object has type different than T
public static T DbHelper.FromID<T>(string base64Id)
{
    return FromID(Base64DecodeObjectID(base64Id)) as T;
}
```

@Starcounter/sc-apps WDYT?

**Comment by miyconst** [comment]
This subject has been discussed many many times, but every time it was pushed for the "better times". And this issue is a duplicate of - [Methods to retrieve objects by identity](https://github.com/Starcounter/level1/issues/2567).

Still, I really hope we could push a proper fix (even if it's a breaking change) for naming before Starcounter 3.0.

**Comment by joozek78** [comment]
Duplicate of starcounter/level1#2567
