### ISSUE TITLE
Unable to drop table when table name is not part of Schema

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Home#123]
SC Version 2.3.0.5943

We have removed a table (ClassifiedBroadAd) from our project. after building and running the project.

When we try to delete records from the table (makes sense, this table is not part of DB Schema anymore):
![image](https://cloud.githubusercontent.com/assets/4388707/26354551/48a797da-3fc5-11e7-8639-a5ba2aea8e37.png)

When we try to drop table: 
![image](https://cloud.githubusercontent.com/assets/4388707/26354561/56b17512-3fc5-11e7-819f-4470732ac3f9.png)

When we try to drop index:
![image](https://cloud.githubusercontent.com/assets/4388707/26354535/32d21e76-3fc5-11e7-95f4-5b4221c9189f.png)

**Comment by miyconst** [comment]
So, to summarize:

- To execute `DROP TABLE` we have to drop index first.
- To execute `DROP INDEX` the CLR class for the table is required.
- **Means it is not possible to drop a table with an index if the CLR class is no longer available.**

cc @k-rus

**Comment by k-rus** [comment]
> So, to summarize:
> 
> To execute DROP TABLE we have to drop index first.
> To execute DROP INDEX the CLR class for the table is required.
> Means it is not possible to drop a table with an index if the CLR class is no longer available.
> cc @k-rus

You are correct, it is not possible to drop index for a table, which has no loaded CLR class.

Latest 2.3 version of Starcounter (since [April 28](https://teamcity.starcounter.org/viewLog.html?buildTypeId=Starcounter_V23NightlyWindows&buildId=24045) uses NewSQL for DROP INDEX, which doesn't require loading CLR class. Actually it also implements SQL standard semantics for DROP TABLE and allows to drop tables with data and indexes.

**Comment by miyconst** [comment]
Thanks @k-rus for the answer!

Then there are two solutions:

1. Return back the CLR class, drop index, drop table, delete CLR class.
2. Upgrade to the latest 2.3.1 and drop table.
