### ISSUE TITLE
Starcounter SQL performance

### ISSUE THREAD

**Issue by papusa** [Starcounter/Home#124]
Hi,

I have created 1m records in database. Here is a code of how data was created:

```
var random = new Random();
Db.Transact(() => {
	for (int i = 0; i < 1000000; i++) {
		new Room {
			FloorNumber = random.Next(1, 100),
                        RoomNumber = random.Next(1, 10000),
                        Description = "Test"
        };
    }
});
```

Now when SQL query is done via our app it's working slowly. For example count query:
![getroomscount_perf_report](https://cloud.githubusercontent.com/assets/23210354/26491620/0d424bee-4219-11e7-9bc7-018bf090c6a8.PNG)
![getroomscount](https://cloud.githubusercontent.com/assets/23210354/26491623/10bbeb72-4219-11e7-9b28-684cec0ed359.PNG)

From screens can be seen that COUNT query is taking almost 6 seconds which is unacceptable for us.

What am I doing wrong?

My environment:
![image](https://cloud.githubusercontent.com/assets/23210354/26491739/7784e930-4219-11e7-91c4-7fdca7ce58f9.png)
Starcounter version: Starcounter-RC-2.3.1.6402 (Apr 29, 2017 2:02:07 AM)

Thanks

**Comment by mmnosek** [comment]
I assume, that you have no index on the `IsActive` column, so Full Table Scan is performed.  It's quite easy to declare the index: https://docs.starcounter.io/guides/SQL/indexes/

Please, let me know what are the results when this column is indexed.

**Comment by mmnosek** [comment]
So, after discussion: `IsActive` column is calculated property, it is doing another query: 

```
public bool IsActive => Db.SQL<long>($"SELECT COUNT(sh) FROM {typeof(StatusHistory)} sh WHERE sh.\"From\" <= ? AND sh.\"To\" >= ? AND sh.Resource = ?",
            DateTime.Today,
            DateTime.Today, this).First == 0 ? true : false;
```

Index for this query does not help.

cc @per-samuelsson

**Comment by miyconst** [comment]
There should be an index for all the columns included in the `WHERE` clause.

```sql
CREATE INDEX StatusHistory_From_To_Resource ON StatusHistory (From, To, Resource); 
```

**Comment by papusa** [comment]
@miyconst 
We have tried that. A bit better, but still slowly.

**Comment by miyconst** [comment]
Another improvement is replacing this with:

```cs
public bool IsActive => Db.SQL<long>($"SELECT COUNT(sh) FROM {typeof(StatusHistory)} sh WHERE sh.\"From\" <= ? AND sh.\"To\" >= ? AND sh.Resource = ?",
            DateTime.Today,
            DateTime.Today, this).First == 0 ? true : false;
```

```cs
public bool IsActive => Db.SQL<StatusHistory>($"SELECT sh FROM {typeof(StatusHistory)} sh WHERE sh.\"From\" <= ? AND sh.\"To\" >= ? AND sh.Resource = ?",
            DateTime.Today,
            DateTime.Today, this).First != null;
```

**Comment by miyconst** [comment]
How many rows in the `StatusHistory` table?

**Comment by papusa** [comment]
@miyconst 
1) I tried that code as well - no difference
2) 7 records

**Comment by miyconst** [comment]
Could you please share your database classes declaration and the code to generate the test data? It should include both `StatusHistory` and `Room` classes.

**Comment by papusa** [comment]
Here is a "Resource" class a parent for "Room" :

**Comment by k-rus** [comment]
How big is `StatusHistory`? I guess it can be big. `GetRoomsCount` iterates over each raw of `Room` table and each iteration calls `IsActive`, which iterates over `StatusHistory`. This can easily lead to the performance number reported.

`IsActive` implemented as:

```c#
public bool IsActive => Db.SQL<long>($"SELECT COUNT(sh) FROM {typeof(StatusHistory)} sh WHERE sh.\"From\" <= ? AND sh.\"To\" >= ? AND sh.Resource = ?",
            DateTime.Today,
            DateTime.Today, this).First == 0;
```

To make `GetRoomsCount` fast `IsActive` query should go through small number of raws, since it is then multiplied by 1000000. I guess the result set for COUNT is small, since the same room cannot be have active status more than once, right?

Then It can be useful to look into query plan and try to play with the query to access only small number of records. 

Note that compound indexes does not work for other comparions than equality, https://github.com/Starcounter/level1/issues/1772

**Comment by TakhirMamirov** [comment]
Actually, the room is INactive if there exist any of the StatusHistory records, which correspond the rule:
(From <= TODAY <= To). So we only need to look for the first record that meet this criteria. Which Starcounter SQL would allow to correctly write such check to check if there exists at least one matching record?

**Comment by k-rus** [comment]
> Actually, the room is INactive if there exist any of the StatusHistory records, which correspond the rule:
> (From <= TODAY <= To). So we only need to look for the first record that meet this criteria. Which Starcounter SQL would allow to correctly write such check to check if there exists at least one matching record?

You can remove count and check if result is empty:

```c#
public bool IsActive => Db.SQL<long>($"SELECT sh FROM {typeof(StatusHistory)} sh WHERE sh.\"From\" <= ? AND sh.\"To\" >= ? AND sh.Resource = ?",
            DateTime.Today,
            DateTime.Today, this).First == null;
```
Disclaimer: I haven't run or compiled the code, but I don't see why it shouldn't work.

In the above case, if a status history satisfying the condition is found, it will be emitted and query execution will stop due to `First`.

This might reduce execution time by half, if index is not utilised.

By the way, how many status history records, which satisfy condition for the resource, can be presented? One or more?

**Comment by papusa** [comment]
@k-rus 

> How big is StatusHistory? I guess it can be big.
What do you mean?

```C#
public bool IsActive => Db.SQL<long>($"SELECT COUNT(sh) FROM {typeof(StatusHistory)} sh WHERE sh.\"From\" <= ? AND sh.\"To\" >= ? AND sh.Resource = ?",
            DateTime.Today,
            DateTime.Today, this).First == 0;
```

I've been trying similar code and it doesn't worked faster for me.

**Comment by TakhirMamirov** [comment]
@k-rus, tried suggested code, no improvement.

As regards to the amount of satisfying records - it can be more than one. The StatusHistory table keeps the Room reservation periods by persons (and maintenance periods as well), therefore, if a Room is booked by three persons for the same period, there will be three records which satisfy the requirements. But we shouldn't care about how many records satisfy - it's enough to check if there at least one record matches, making the Room inactive at that date.

**Comment by k-rus** [comment]
Thank you for clarifying about selectivity of inactive records per room. Since it is almost one, removing `count` doesn't improve situation. It might improve by half, but you need order of magnitude improvement. In general, using `count` in such case is not good practice as queries will take more time to execute by design compare with `.First`.

I don't know how much it is possible to improve performance by tweaking queries, since compound index cannot be utilised fully due to current Starcounter implementation, or without re-desiging the application schema.

To tweak the performance look into query plan, or may be, combine two queries into one, which can be tricky.

**Comment by k-rus** [comment]
By the way, is the query replaced with static string at compile time?

**Comment by TakhirMamirov** [comment]
> By the way, is the query replaced with static string at compile time?

How can I check it?

**Comment by k-rus** [comment]
> By the way, is the query replaced with static string at compile time?
> How can I check it?

Take the binary and disassembly from IL into C# back. For example, use ILspy.

**Comment by TakhirMamirov** [comment]
Just to get back to the original problem, we need to calculate amount of records to show amount of pages in pagination element on UI. Since the first page is shown quickly enough, the solution also might be to run that query in an async mode, show spinner instead of pagination element, and in a few seconds, after task is completed, show pagination. While it can be solved this way, I'm a little concerned about performance of similar cases in the future, for other business.

**Comment by miyconst** [comment]
>While it can be solved this way...

It can be solves in scope of a single user. If you have many users, and all of them will load the database, the performance will start to degrade significantly.

@k-rus please recommend a solution with different database schema, which would work efficient.

**Comment by k-rus** [comment]
Currently I don't have suggestions how to improve design or query. To move forward with query tweaking: what are index definitions on the tables? What are the query plans for the two queries?

**Comment by miyconst** [comment]
@TakhirMamirov, @papusa please provide full info about the issue, which is:

- Declaration of both database classes. You can omit properties and functions which are not related to the issue.
- Number of records in each table.
- Index declaration.
- SQL queries itself.
- Query execution plan for both of the queries.

**Comment by k-rus** [comment]
> By the way, is the query replaced with static string at compile time?
> How can I check it?
> Take the binary and disassembly from IL into C# back. For example, use ILspy.

And this question is still interesting.

**Comment by miyconst** [comment]
>Take the binary and disassembly from IL into C# back. For example, use ILspy.

Or just use a plain string for the testing purposes if disassembly is time consuming.

**Comment by k-rus** [comment]
It was investigated that compound index can be utilised for range queries like in above example.

**Comment by TakhirMamirov** [comment]
I plan to set up a regular code-first (EF) project with MS SQL database, create those two tables and run the same query. Your bets about performance difference in between Starcounter's approach and regular one?

**Comment by k-rus** [comment]
> I plan to set up a regular code-first (EF) project with MS SQL database, create those two tables and run the same query. Your bets about performance difference in between Starcounter's approach and regular one?

Are you going to measure load with request responds from many client machines calling different handles?

**Comment by k-rus** [comment]
> By the way, is the query replaced with static string at compile time?
> How can I check it?
> Take the binary and disassembly from IL into C# back. For example, use ILspy.
> And this question is still interesting.

I have tested this. The implementation does many heap object allocations at runtime: `string.Format` is used, which creates `StringBuilder` and so on. cc @miyconst

**Comment by joozek78** [comment]
@k-rus does it hit the performance significantly?

**Comment by TakhirMamirov** [comment]
So here is what I came to:

1. I got rid of on-the-fly calculation of IsActive for millions of records;
2. Instead, I now walk through StatusHistory table and select all matching by date records;
3. Then retrieve parent Resource (Room) object and applying .Distinct() over the result set, since each Resource linked as on-to-many with StatusHistory records.

As we have selection to show either Active or Inactive resources in lookup, both methods are equal:

```
public static IEnumerable<Resource> GetInactive => Db.SQL<StatusHistory>($"SELECT sh FROM {typeof(StatusHistory)} sh WHERE sh.\"To\" >= ? AND sh.\"From\" <= ? ", DateTime.Today, DateTime.Today)
        .Select(x => x.Resource)
        .Distinct();
```

```
public static IEnumerable<Resource> GetActive => Db.SQL<StatusHistory>($"SELECT sh FROM {typeof(StatusHistory)} sh WHERE sh.\"To\" < ?", DateTime.Today)
            .Select(x => x.Resource)
            .Distinct();
```

So now we have "simple" select. In my test set I have 1m resources, each has 2 StatusHistory records, thus the whole StatusHistory table has 2m records. So, suppose of all my resources are inactive, then GetInactive() takes around 2 sec. It's a bit better than original 5 sec.

Could it be further improved or it is a limit?

**Comment by k-rus** [comment]
> @k-rus does it hit the performance significantly?

I am not an expert in C# to answer this. It is certainly overhead of calling all constructors and destructors. Since the allocated obejcts are short-living, memory allocation and garbage collecting should not be bad. I advise you to look into the actual code, which is called for the case.
Actually I made microbenchmark to compare constructing query string by both way and the difference is 2000 times. How big the actual overhead will depend on the other code. 

>So now we have "simple" select. In my test set I have 1m resources, each has 2 StatusHistory records, thus the whole StatusHistory table has 2m records. So, suppose of all my resources are inactive, then GetInactive() takes around 2 sec. It's a bit better than original 5 sec.

> Could it be further improved or it is a limit?

I just reiterate. The query goes through 2 millions of records in 2 seconds, i.e., 1 mcs per record, right? Then it is expected performance with current implementation of SQL. The only way to improve is to retrieve data by portions, if it suits the application need. I believe Offsetkey can help it, but it requires care in its use (if it still works), since it is an experimental feature with some known bugs.

**Comment by miyconst** [comment]
@TakhirMamirov and @papusa, I have made comparison between Entity Framework and Starcounter using exactly the same database. The `Room` table had `250 000` rows, while `Reservation` had `2 000 000` rows. And the results are as following:

- Using string interpolation is very expensive, and may lead to 50%-80% extra time for query execution.
- Sub-query execution, as implemented in the `IsActive` property slightly faster using MS-SQL.
- In Starcounter the most efficient way is to use `Distinct` on top of the `Select` from the `Reservation` table. @TakhirMamirov you are already using this approach in the previous comment.

All in all, the count operation returns just a single value, which means EntityFramework does not lose much compare to Starcounter, and the performance is very equal.

The test was performed in the ideal situation, which will never happen in the real life. Single request to calculate count of free rooms for a date. 

You should be aware, that the free version of MS-SQL has [certain restrictions](https://www.microsoft.com/en-us/sql-server/sql-server-2016-editions) on how many CPU cores and RAM can be used. This means that the more load you have, the worse performance will be.

For certain reasons I cannot publish the benchmark numbers I have got, but if you are interesting, please let me know and I will share my code, so you can run the benchmarks yourself.

>Could it be further improved or it is a limit?

Currently this is the limit. Unfortunately Starcounter does not yet support `COUNT(DISTINCT *)` operation, which requires applying `Distinct` on top of the query. You should expect slight performance improvements when the `COUNT(DISTINCT *)` construction is implemented.
