### ISSUE TITLE
Generating JSON from template string and properly populating JSON arrays

### ISSUE THREAD

**Issue by erikvk** [Starcounter/Home#126]
I'm trying to generate a Typed JSON using the following template:

```
"BidRules$": [{
	"Conditions$": [{
		"Key$": "",
		"Operator$": "",
                "Value$": "@RESTar()"
	}],
	"BidTemplates$": [{
		"Price$": {
			"Amount$": 0,
			"Currency$": "nil",
			"CPM$": false
		},
		"AdIds$": [""]
	}]
}],

```

By means of `var myJson = new Json(template);`
And then populating it with:

```
"BidRules$": [{
	"Conditions$": [{
		"Key$": "Site.Domain",
		"Operator$": "CONTAINS",
		"Value$": "@RESTar(\"familjeliv\")"
	}],
	"BidTemplates$": [{
		"Price$": {
			"Amount$": 25.000000,
			"Currency$": "USD",
			"CPM$": true
		},
		"AdIds$": []
	}]
}],
```

By means of `myJson.PopulateFromJson(json);`

I then end up with:

```
"BidRules$": [{
	"Conditions$": [{
		"Key$": "",
		"Operator$": "",
		"Value$": "@RESTar()"
	}],
	"BidTemplates$": [{
		"Price$": {
			"Amount$": 0,
			"Currency$": "nil",
			"CPM$": false
		},
		"AdIds$": [""]
	}]
}, {
	"Conditions$": [{
		"Key$": "Site.Domain",
		"Operator$": "CONTAINS",
		"Value$": "@RESTar(\"familjeliv\")"
	}],
	"BidTemplates$": [{
		"Price$": {
			"Amount$": 25,
			"Currency$": "USD",
			"CPM$": true
		},
		"AdIds$": []
	}]
}]

```

Which, of course, is not what I want.

Is there any way to make sure that template objects in arrays are replaced when the template is populated with real data?

(the template and json above are abbreviated. the trees are actually larger)

@chrhol

**Comment by chrhol** [comment]
The problem here is the functionality of the constructor that takes a string, it actually calls `PopulateFromJson` using the json that was submitted.

```csharp
public Json(string jsonStr) : this() {
    this.Template = TObject.CreateFromJson(jsonStr);
    this.PopulateFromJson(jsonStr);
}
```

This mean, as you noted, that the values that are used for the template will be included as values. 

I'm not sure what the best way is to improve this, and make the API more logical. We need to review it.

What you can do right now is to instead sending in the template-string directly to the constructor, just create a `Template` instance from it, and then use that instance when creating the `Json`

```csharp
using Starcounter;
using Starcounter.Templates;
...
var template = (TObject)TObject.CreateFromJson(JSON);
var typedJson = new Json() { Template = template };
typedJson.PopulateFromJson(json);
```

**Comment by erikvk** [comment]
Thanks, I'll try that right away.

**Comment by chrhol** [comment]
I will close this as answered.
