### ISSUE TITLE
Question: way to structure polymer app

### ISSUE THREAD

**Issue by iSuslov** [Starcounter/Home#164]
Hi guys, I'm pretty new to your technology, just figuring it out, and I want to know is it possible to structure polymer app in its classic way in the folder `src/MyApp/wwwroot`:
 - `bower_components`
 - `src` 
 - `index.html`

Why should we use folder `sys`? What it the purpose to name it like that?
How to manage dependencies with `bower`?

**Comment by miyconst** [comment]
@iSuslov please read this page - [Using Web Components](https://docs.starcounter.io/guides/web-apps/using-web-components/).

**Comment by miyconst** [comment]
>Hi guys, I'm pretty new to your technology, just figuring it out, and I want to know is it possible to structure polymer app in its classic way in the folder `src/MyApp/wwwroot`:

In sort:

- Yes, it is possible to structure the app in the way you describe.
- No, it won't work as you expect.

Because:

- Starcounter includes Polymer and WebComponents.js from `/sys/` folder, that is why all bower components should also be installed into the `/sys/` folder to avoid double loading.
- When multiple apps are started within a database, the `wwwroot` folder from all apps will be served as the static content folder. That means, if there is `/wwwroot/index.html` file in both apps, the files will overwrite each other. That is why all app specific content should be placed in the `/wwwroot/app_name/` folder.

**Comment by Mackiovello** [comment]
Welcome @iSuslov! You could also take a look at our [proposed project structure](https://docs.starcounter.io/cookbook/project-structure/) to see if that's helpful. If you have any more questions, don't hesitate to ask.
