### ISSUE TITLE
Can I use Handle.Tcp/Udp?

### ISSUE THREAD

**Issue by SenerDemiral** [Starcounter/Home#199]
Will it be depreciated like Http.GET and Starcounter.Node?
[https://github.com/Starcounter/level1/issues/4166#issuecomment-288390578](url)

**Comment by Mackiovello** [comment]
@alemoi do we have an answer for this?

**Comment by alemoi** [comment]
Thanks for the great question! I thought to deprecate but now I'm think to keep the `Http.GET` API and change the internals to use native .NET. `Starcounter.Node` I am thinking to actually deprecate. Do you use it?

However, when it comes to users, I would really suggest using native .NET HTTP capabilities, because that's the direction we are going long term.

**Comment by SenerDemiral** [comment]
I didn't use Http.Get and Starcounter.Node. I used WebClient.

But I'm using Handle.Udp for IoT data collection project. 
What do you suggest, System.Net.Sockets.UdpClient or Handle.Udp?

**Comment by alemoi** [comment]
@SenerDemiral I would actually suggest using `System.Net.Sockets.UdpClient` because in future we will go for standardized Go gateway that does not support UDP, as far as I remember. @linkdata can provide more info on whether there can be UDP support there.

**Comment by linkdata** [comment]
UDP forwarding won't be part of the feature set for the RAP gateway, sorry.

**Comment by miyconst** [comment]
Closing the issue as answered question.
