### ISSUE TITLE
Querying in Admin is extremely slow

### ISSUE THREAD

**Issue by mmnosek** [Starcounter/Home#239]
Running queries in Admin is extremely slow, sometimes it even kills the browser. I started debugging from SQL performance, but then realized it's not a problem. Results are returned very fast, but then it takes a lot to see results on the screen.

*How to reproduce*?
* Run some application
* Open Admin panel
* Write some query that will return at least couple hundreds of records. For example: `SELECT c.* FROM Simplified.Ring2.Something c`

An interesting thing happens if you open dev tools on network/console and repeat steps above:
![starcounter_administrator](https://user-images.githubusercontent.com/4943949/30384317-4800729c-98a4-11e7-8136-1f599e2904fc.png)

A request is generated for every single row returned. It returns `404`

It's hard for me to judge where the problem exactly is. Console says `palindrom.js`

@alshakero - please have a look if it's not related to latest Palindrom upgrade
@ubbeK @Mihaiii - could you have a look what has been changed recently in Admin?

cc @warpech 

Bug was introduced for sure in 2.3.1 - works fine in 2.3.0 channel.
Starcounter version used to reproduce: 2.3.1.7166

**Comment by Mihaiii** [comment]
It works ok with 2.3.1.6860 (uses PuppetJS), throws errors in different situations in 2.3.1.6870 (uses Palindrom 3.0.0).
Because running Administrator app with Palindrom causes multiple problems (in some situations when you want to start/stop an app nothing happens etc.) I think it's best to use PuppetJS for Administrator app **for the moment**, unless someone else has a better idea. 
@alshakero Could you please give more info about this comment and change? What was the main reason for that change? (there are errors before and after that change. I'm just asking for context.)
https://github.com/Starcounter/level1/commit/2667d3eaa485d3721cf7d0dac91def12505c7d32#diff-e5c27aaac048ac0634b9f8a82582c4d2R45 .

**Comment by mmnosek** [comment]
Thanks @Mihaiii for the investigation!

Your solution seems to work, but I would rather prefer to address the original issue. Could you find when and where exactly this change was introduced? We should ask to do it properly instead :)

**Comment by Mihaiii** [comment]
> Could you find when and where exactly this change was introduced? We should ask to do it properly instead :)

I assumed that it was when the transition from PuppetJS to Palindrom 3.0.0 was made, but you're right, I'll narrow it down (I'll edit this post) :)

**Comment by Mihaiii** [comment]
> Could you find when and where exactly this change was introduced? We should ask to do it properly instead :)

Those errors appear starting with [this commit](https://github.com/Starcounter/level1/commit/589bea553a65088c1f3c19af81726aca1a28040b), so when the transition from PuppetJS to Palindrom was made.

**Comment by warpech** [comment]
Please check after https://github.com/Starcounter/level1/pull/4266 is merged. This should fix the problem in my opinion.

**Comment by Mihaiii** [comment]
Performance will definitely improve after Starcounter/level1#4266 is merged, but errors will still be there so for example if from `http://localhost:8181/#/databases/default` (assuming there is a `default` database) you click on `App Warehouse` and then on the home icon, you'll have to refresh the page to start/stop an app.

**Comment by Mihaiii** [comment]
https://github.com/Starcounter/level1/pull/4266 is merged. Please see latest RC.

**Comment by mmnosek** [comment]
I've tried Starcounter-RC-2.3.1.7356 and it still has exactly the same problem. Please have a look.

**Comment by Mihaiii** [comment]
I think that @warpech was referring to the performance problem (which was definitely improved because Administrator is now using Palindrom 3.0.5). Other than that, https://github.com/Starcounter/level1/pull/4278 was never meant to solve the errors presented in the first message.

I consider this issue a duplicate of #258 and in my opinion one of the topics should be closed.

**Comment by mmnosek** [comment]
Performance is not improved at all after the upgrade. Errors and hundreds 404 requests cause serious performance issue. What do we need to fix it? Is it Palindrom or Admin problem? It seriously affects user experience and first impression.

**Comment by alshakero** [comment]
I fixed this. Is there a PR I can push to or should I create a branch?

**Comment by Mihaiii** [comment]
Please create a branch.

**Comment by mmnosek** [comment]
Thank you all for fixing this!
