### ISSUE TITLE
Migrating an app from 2.3 to 2.4

### ISSUE THREAD

**Issue by warpech** [Starcounter/Home#246]
When I try to build https://github.com/StarcounterApps/KitchenSink/tree/d42dba70007a1be2fe7987de6460910967232e3c in Starcoutner 2.4 (using `msbuild` via `build.bat` in the Windows console), I get the following error:

```
KitchenSink.csproj : error : This project specifies no Starcounter version compatibility. For Starcounter versions 2.
4 and above, that is a requirement. By using versions >= 2.x of the Starcounter Visual Studio extension, projects are p
roperly configured from start. If you want to configure the project yourself, set property `StarcounterVersionCompatibi
lity' to '2.4'. Please see https://github.com/Starcounter/Starcounter.VisualStudio/wiki/Version-compatibility if you ne
ed further help. [c:\www\KitchenSink\src\KitchenSink\KitchenSink.csproj]
```

The URL provided https://github.com/Starcounter/Starcounter.VisualStudio/wiki/Version-compatibility does not contain any helpful information about how to upgrade the project. Any clues how to continue?

![2017-09-21 22_59_26-command prompt](https://user-images.githubusercontent.com/566463/30718631-cb8ff9ac-9f20-11e7-8b15-43c36c16e103.png)

**Comment by Mihaiii** [comment]
Related with https://github.com/Starcounter/level1/issues/4143

**Comment by warpech** [comment]
Thank you for finding a related issue. Yes, it turned out that I need to add `<StarcounterVersionCompatibility>2.4</StarcounterVersionCompatibility>` to the first `<PropertyGroup>` section in `.csproj`.

Please close this issue when that is properly described in the page linked in the OT or in the Docs.

**Comment by per-samuelsson** [comment]
FWIW, I have put an issue in 2.4 / Odessa that we really want to improve on this. Basically, what is there now is to avoid weird scenarios caused by incompatible project setup between 2.3 and 2.4, forcing users to pay attention when switching between 2.3 -> 2.4 and vice versa.

The aim must be to support only a single extension version for both those Starcounter versions, and also support one project to run on both, without changing settings.

**Comment by warpech** [comment]
Because of `<StarcounterVersionCompatibility>2.4</StarcounterVersionCompatibility>`, we ended up with redundant branches in our apps. See: https://github.com/Starcounter/RebelsLounge/issues/218

Must we have a separate branch for 2.4? 

Can Starcounter 2.3.1 build a `.csproj` that has `<StarcounterVersionCompatibility>2.4</StarcounterVersionCompatibility>`?

**Comment by per-samuelsson** [comment]
> Can Starcounter 2.3.1 build a .csproj that has <StarcounterVersionCompatibility>2.4</StarcounterVersionCompatibility>?

It's in the near pipeline to improve on this, with efforts already started: https://github.com/Starcounter/level1/issues/4365

The aim is to drop StarcounterVersionCompatibility completely and also do our best to have only one single version of the extension. We aren't really there yet though. Sorry. 😢

**Comment by per-samuelsson** [comment]
Oh, and the answer to

> Can Starcounter 2.3.1 build a .csproj that has 2.4?

is no. The idea with explicit compatibility was to force users to pay attention when going 2.3 -> 2.4 **and vice versa** because we expect project references to differ.

**Comment by warpech** [comment]
Right now it is a pain in the neck, because it forces us to have two `master` branches and merge like this:

```
feature-branch --> master --> master-2.4
```

This is awful, because a PR can only be tested in 2.3.1. We want to be able to test the PR of `feature-branch` both for 2.3.1 and 2.4.

**Comment by per-samuelsson** [comment]
> ... because it forces us to have two `master` branches and merge like this:
> 
> ```
> feature-branch --> master --> master-2.4
> ```

Not sure I understand why? We have 2 compatibility modes - one for 2.3 and one for 2.4. That would force you to have two branches, targeting each version of Starcounter. Feature branches would always just be short-living ones, no?

**Comment by warpech** [comment]
> Feature branches would always just be short-living ones, no?

Exactly. I want to have a single feature branch and a single PR. That branch should be tested on TeamCity with Starcounter 2.3 and Starcounter 2.4.1, so I need single codebase that runs in those two versions.

**Comment by per-samuelsson** [comment]
> I want to have a single feature branch and a single PR. That branch should be tested on TeamCity with Starcounter 2.3 and Starcounter 2.4.1, so I need single codebase that runs in those two versions.

Well, yeah, I understand. That's the optimal of course. And we actually *have* decided that we want to try to get 2.3 and 2.4 compatible wrt project settings. I'm not sure exactly how still though (since things have changed, deliberately).

The situation is not really unique though. And remember: 2.4 is still considered bleeding edge. It's a 1-1 compare to how Starcounter itself is currently structured: we have one branch for 2.3 and one for 2.4/Odessa (develop). When we introduce a change that affect both versions, we need to test both in isolation. We really don't expect that to change ever really.

I suggest that for now, if you think it's a pain, you treat all your `master-2.4` branches as bleeding edge too. Meaning they can break at any time, when something comes merging from 2.3. And if they do, you deal with it (tweak it as necessary).

**Comment by per-samuelsson** [comment]
If this is a pain for you, big enough for you to be willing to contribute to a solution, take a look at section [How do I migrate a project from 2.3 -2.4 and vice versa](https://github.com/Starcounter/Starcounter.VisualStudio/wiki/Version-compatibility#how-do-i-migrate-a-project-from-21-3--24-or-vice-versa) and submit suggestions on what we could do to address those incompatibilities. Would be highly appreciated!

**Comment by per-samuelsson** [comment]
Just for the record, me and @warpech had a rather lengthy discussion about this off-tracker.

One thing we discussed was that one "quick fix" for this problem is to simply remove entirely the check for version compatibility in build targets. Meaning devs are on their own - if they move projects back and forth between 2.3 <-> 2.4, some features might not work properly unless they explicitly update their project settings. Such features include unit testing and self-hosting, and it's quite possible that error reporting is not very accurate.

If a decision is taken to go that way, I can volunteer fixing it in both version - it should be pretty simple. But before that, I would want someone else to do some initial testing. It should be pretty easy to test these scenarios locally, and you would't even have to build a custom version of Starcounter - disabling the version compatibility check is just a matter of changing a target in local `Starcounter.MsBuild.targets`.

If you decide on that, let me know and I can provide some simple instructions. / advice.

**Comment by warpech** [comment]
Yesterday @joozek78 made a solution that works for us now in KitchenSink. It is best describe on the picture:

![image](https://user-images.githubusercontent.com/566463/34199276-90751828-e56d-11e7-81ba-345fb9e825e7.png)

Whenever someone commits to a feature branch (orange color on the diagram), the TeamCity configuration "KitchenSink Test Feature Branch" will trigger two builds:

- KitchenSink Master branch with Starcounter RC (2.3.1) - to test the feature branch (orange)
- KitchenSink Master-2.4 branch with Starcounter Develop (2.4) - automatically creates a temporary branch that works with 2.4 (green)

I will play with it a bit. I think this is a fine solution.

**Comment by warpech** [comment]
Closing as "won't fix" because a clone of this issued was closed with such resolution: https://github.com/Starcounter/Home/issues/353
