### ISSUE TITLE
Temp directory is not deleted

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Home#256]
Inside `Documents/Starcounter/Personal` there is `Temp` directory that (in my case) takes almost as much space as `Data` (5.5GB vs 5.9GB). It is not deleted after starcounter exits (`staradmin kill all`) neither when it's restarted (`staradmin start server` `star App.exe`). Thus I have to conclusion:

1. If it's really temporary Starcounter should take care to delete it (if the `staradmin kill all` doesn't leave a chance for that it should be cleaned up after it starts again)
1. If it shouldn't be deleted, then it's not temporary - we should rename it to avoid ambiguity

I'm only raising this issue because of considerable size of this directory - it looks like it matches the `Data` directory

**Comment by per-samuelsson** [comment]
> I'm only raising this issue because of considerable size of this directory - it looks like it matches the `Data` directory

That is just by coincidence. They contain completely different things.

This issue is already known and tracked, but never has been prioritized. Main issue https://github.com/Starcounter/level1/issues/1690, and related https://github.com/Starcounter/level1/issues/2007.

I suggest we close this as a dup, but I guess you guys @joozek78 and @miyconst decide on that, and how to prio.

**Comment by miyconst** [comment]
Closing as duplicate.
