### ISSUE TITLE
Setting JSON properties as unbound with IExplicitBound doesn't work

### ISSUE THREAD

**Issue by Mackiovello** [Starcounter/Home#257]
To opt-out of `IExplicitBound`, the `Bind` property should be set to `null`. That makes sense. What is confusing is that setting `BindingStrategy` to `Unbound` doesn't work, the compiler still gives an error. 

Would it be possible to use `BindingStrategy.Unbound` to opt out of `IExplicitBound`?

**Comment by chrhol** [comment]
Yes, it should work the same. This sounds like a bug.

I'll assign it to me to fix it.

**Comment by chrhol** [comment]
I thought this was a simpl bug to fix, but it turns out that support for it needs to be added to the code-behind parser and some changes in codegenerator for TypedJSON. Since we are not decided yet what the future of TypedJSON should be it seems to not be worth the time to fix this. Do you agree @miyconst?

**Comment by miyconst** [comment]
Agree. It's labeled as `nice to have`, so let's keep it for until we decide where we move with Typed JSON.

**Comment by miyconst** [comment]
Closing as won't fix in Starcounter 2.4 and not applicable in Starcounter 3.0.
