### ISSUE TITLE
How to set culture info?

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Home#267]
I am trying to set custom culture info in a Starcounter application, which does not seem to work.

Here is what I do on application startup and inside every handler.

```cs
System.Threading.Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("xx-XX");
```

But when a JSON patch received, the culture info is randomly reset to the server's default value.

Is it possible to specify global culture info for an application?

cc @chrhol, @alemoi

**Comment by chrhol** [comment]
> Is it possible to specify global culture info for an application?

Currently the answer would be no. We have a very limited concept of application-specific configuration (or application context at all) in place today. Although there is a `Application` instance that can be retrieved (with `Application.Current`) and used for these kind of settings.

> But when a JSON patch received, the culture info is randomly reset to the server's default value.

I would guess that it's not reset, but a different thread is scheduled from what you set the value on.

To get this to work, we need to set the correct values each time we switch context of current executing application (which can happen several times during a request).

Or if you mean you want to have one global setting for one codehost, it would be a bit simpler. But we still need to make sure we set the correct culture each time a task (or a new thread) is executed. 

I guess you could also set `CultureInfo.DefaultThreadCurrentCulture`, but that feels like a hack, since anyone can change this value so you are never sure that the culture you want is the one used.

**Comment by miyconst** [comment]
>`CultureInfo.DefaultThreadCurrentCulture`

This works for me. Thank you for the answer. Closing the issue.
