### ISSUE TITLE
"star error" command

### ISSUE THREAD

**Issue by mtornwall** [Starcounter/Home#273]
Would be nice to have a `perror`-like utility that prints the name and message for a Starcounter error code, eg:

    C:\> star error 1070
    ScErrUnexpectedInternalError (SCERR1070): An unexpected internal error was detected.

**Comment by per-samuelsson** [comment]
Not a perfect 1-1, since what we've got open help in the browser, but FWIW: we've had this feature since ages. 😎 

![image](https://user-images.githubusercontent.com/2902045/31573625-be20a6bc-b0bf-11e7-9e1a-62252fd0f726.png)

There in also an old issue about tweaking it: https://github.com/Starcounter/level1/issues/2109

**Comment by mtornwall** [comment]
Thanks for pointing that out @per-samuelsson, I had no idea!

I still think my proposal would be useful though.

**Comment by per-samuelsson** [comment]
> I still think my proposal would be useful though.

Agree. We should drop the current one, redesign it in `staradmin` (or whatever future tooling) and keep stuff in the CLI. Generally, these kind of tools shouldn't pop up windows, unless explicitly told so.

cc @ubbeK

**Comment by Mackiovello** [comment]
Closing in favor of https://github.com/Starcounter/Starcounter.Nova.Cli/issues/24

We're creating the new CLI in that repo, so it makes sense to have this issue there.
