### ISSUE TITLE
Http.POST does not accept HTTPS

### ISSUE THREAD

**Issue by jwillmer** [Starcounter/Home#284]
![https bug](https://user-images.githubusercontent.com/1503577/31945746-5b42df4c-b8d0-11e7-8c7c-230df8def4b2.png)

Is this a bug or intentionally that I can't use `Starcounter.Http` for sending HTTPS (post) requests? Is there a recommended way of sending HTTPS requests - `System.Net.Http`?

**Comment by RickardR** [comment]
Interested in this too, we're going to need to consume some external rest sources both GET and POST, and they will require https in some cases. Only way is to use HttpClient for this then? Adding https:// only seems to get Node() to try to connect to http://https://XXX and failing on GET.

**Comment by miyconst** [comment]
@jwillmer & @RickardR please be aware that:

- `Http.Post` and other `Http.Xxx` methods are Starcounter proprietary. It was developed long time ago, when .Net native `WebClient` was not yet available.
- Since Starcounter targets multi-platform support, it will be way too expensive to have own HTTP implementation for each stack/platform.
- This API is going to obsolete soon and removed short after.
- There will be no new features.
- Some critical bug fixes may be provided, but not guaranteed.
- **It is always recommended to use standard framework features if available.**

Closing the issue as answered.

**Comment by RickardR** [comment]
Thanks! I interpreted the page on https://docs.starcounter.io/guides/network/external-http-calls/ as I should avoid other libraries, and interpreted that as HttpClient also :). Wasn't aware that HTTPClient weren't intrduced until 4.5 and that's why you previously did your Node/Http implementation. Changing to HTTPClient asap then. Cheers!
