### ISSUE TITLE
Starcounter web admin - starting-executables is not functional

### ISSUE THREAD

**Issue by habib535** [Starcounter/Home#289]
In our documentation for [starting executables](https://docs.starcounter.io/guides/working-with-starcounter/administrator-web-ui#starting-executables), we have mentioned that specifying path to the exe of an app will start the app but I get below error
![image](https://user-images.githubusercontent.com/2991381/32007239-4f80ab7e-b9a9-11e7-968e-f53ea1351148.png)

The app I was trying has just program.cs class and no resource dependency. We also need to enhance this feature so it accepts multiple arguments e.g. `star %* --resourcedir="src\Search\wwwroot" "src/Search/bin/debug/Search.exe"`

A customer reported this issue as he was following the documentation.

**Comment by Mackiovello** [comment]
I added a warning in the docs that this feature doesn't work right now. The warning should be removed when this issue is fixed.

**Comment by mmnosek** [comment]
> I added a warning in the docs that this feature doesn't work right now. The warning should be removed when this issue is fixed.

I don't think we should add anything like this in docs. If something is seriously broken and we know it won't be fixed in the near future - then yes, but not if it's some fixable issue. It's unnecessary work and shows people who read the documentation that things are not working as expected and we don't care - we just add a warning in docs.

**Comment by Mackiovello** [comment]
Warning is removed

**Comment by Mihaiii** [comment]
Closing as done.
