### ISSUE TITLE
Is there a HelloWorld sample without blending?

### ISSUE THREAD

**Issue by SenerDemiral** [Starcounter/Home#302]

**Comment by Mackiovello** [comment]
Hi @SenerDemiral! The current HelloWorld does not use blending: https://github.com/StarcounterApps/HelloWorld

Does that answer your question?

**Comment by SenerDemiral** [comment]
I mean, using imported-template not starcounter-include.
[https://starcounter.io/starcounter-include-non-namespaced-partial-view-models/](url)

**Comment by Mackiovello** [comment]
Exactly, the HelloWorld versioning works differently than most repositories, but the latest version uses `imported-template` and not `starcounter-include`: https://github.com/StarcounterApps/HelloWorld/blob/tutorial-20171106/src/HelloWorld/wwwroot/HelloWorld/PersonJson.html#L22

For more information on `imported-template`, you can read this article that we recently published: https://starcounter.io/starcounter-include-non-namespaced-partial-view-models/

**Comment by Mackiovello** [comment]
Could you explain what you're trying to accomplish? Do you want to completely remove the ability to use blending?

**Comment by SenerDemiral** [comment]
As stated in this article [https://starcounter.io/starcounter-include-non-namespaced-partial-view-models/](url) 
I want to completely remove the ability to use blending.
```
If your partial contains 
only your app internals, 
just modularized, 
and you are consciously don’t want to use any Starcounter features like 
blending, 
custom Shadow DOM compositions fetched from the database, etc. 
If all you need is just a declarative client-side include, 
use imported-template – a custom element made exactly for it.
```

**Comment by Mackiovello** [comment]
Okay, got it. To prevent other applications from blending with your app,  just don't use the `Blender` API, that will make it impossible to blend with your application.

**Comment by Mackiovello** [comment]
You could override `PartialToStandaloneHtmlProvider` to use `imported-template`, but that wouldn't change much for you

**Comment by tomalec** [comment]
What @Mackiovello  proposed:
>  just don't use the Blender API, that will make it impossible to blend with your application.

Is in my opinion easiest way. But it will "remove ability to blend your URL"


If you
> want to **completely** remove the ability to use blending.

There are two ways to achieve that, depending on which part of blending (or both) would you like to block.

If you want to block just client-side part of blending and use only your app response, without Shadow DOM composition features, you need to replace `<starcounter-include partial/view-model="{{foo}}">` with `<template is="imported-template" href="{{foo.YourApp.Html}}" model="{{foo.YourApp}}">`.

 If you want to block also the server-side part that attaches other apps responses not to use blending at all. You will need to 
- replace `Self.GET` on server-side with regular JSON assignment,
- replace `<starcounter-include partial/view-model="{{foo}}">` with `<template is="imported-template" href="{{foo.Html}}" model="{{foo}}">`


If you are in control of everything, you could (if you really want) switch from modular partial views to a monolithic app. Then just put actual code from your partial instead of `<starcounter-include>`

**Comment by SenerDemiral** [comment]
Thank you @tomalec.
I meant that too.
It would be clearer if there was a working sample program.

**Comment by Mackiovello** [comment]
Out of curiosity, why do you not want to use blending? 

I'll consider the question answered. 

We won't create a sample program for this since it goes against our goal of making all our users apply blending so that they can integrate their apps with apps from other Starcounter developers.

**Comment by SenerDemiral** [comment]
Thanks, you considered the question answered already.
Of course I will follow your suggestion and go on the road you show.

Anyway, I did not want to use blending because:
1. I do not use Blender API
2. It is not simple for me.
3. I do not need such complexity.
4. There is a @tomalec blog showing alternative approach. [https://starcounter.io/starcounter-include-non-namespaced-partial-view-models/](url). I thought you had another choice.

**Comment by tomalec** [comment]
Thanks, that seams like a fair list :)

However, I would really appreciate a feedback on 2. - what made it compicated? How we could make it simpler?

**Comment by SenerDemiral** [comment]
Good point!
Simplicity depends on knowledge.
I guess my knowledge is not enough to understand some things.
I appreciate what you try to do with blending.
As a stand-alone person I am asking myself, does it need to be so complicated to mixing multiple apps someone else wrote?
Let's say Sign-in module; many tables out of my control, server-side blending, client-side blending, composition editor, etc..
Maybe I'm too old to know these things.
Do not mind me I'm just mad at myself for not understanding.
Continue your work as you know. I will have to work harder.
Again I apologize for taking your time.

**Comment by Mackiovello** [comment]
Don't apologize, if you feel this, there are others with the same experience too. We really appreciate the feedback.
