### ISSUE TITLE
Iterating over headers in Starcounter.Response

### ISSUE THREAD

**Issue by erikvk** [Starcounter/Home#308]
I would like to iterate over the headers of a `Starcounter.Response` and read names and values. Something like this:

```c#
var response = Http.GET("someUri", ... );
var myDictOfHeaders = new Dictionary<string, string>();
foreach (var header in response.Headers)
     myDictOfHeaders[header.Name] = header.Value;
```

Currently, the only way to do something like this, as far as I know, is to call the `GetAllHeaders()` method of `Starcounter.Response` and parse the returned string. Or is there some other way I am not aware of? @alemoi

**Comment by alemoi** [comment]
@erikvk thanks for the question! There is such thing as `Request.HeadersDictionary` but for responses I would really suggest not using `Http.GET` but standard .NET API, like `HttpClient`, and iterate over headers there.

**Comment by erikvk** [comment]
What if I want to use `Self.GET()` ?

**Comment by alemoi** [comment]
> What if I want to use Self.GET() ?

For that I will try to include the request! :)

**Comment by erikvk** [comment]
I mean, I can do this:

```c#
foreach (var header in scResponse.GetAllHeaders().Split(new[] {"\r\n"}, RemoveEmptyEntries))
{
    var name_value = header.Split(':');
    response.Headers[name_value[0]] = name_value.SafeGet(v => v[1].Trim());
}
```
But it kind of hurts my eyes to just look at that...

**Comment by alemoi** [comment]
We will add this as a feature.

**Comment by erikvk** [comment]
Thank you, @alemoi  :)

**Comment by alemoi** [comment]
I looked into it and it requires a big refactoring unfortunately.
The reason is wrong API that I initially created.
Assumption was that all headers have unique names, which is not true for example for cookies.
I need to change the API to be more like `Dictionary<string, List<string>>` instead of `Dictionary<string, string>`. Many users will have to adopt.
Another thing is that Im waiting for the `Http` class changes, so thinking to fix this issue along the way. Here is the reference: https://github.com/Starcounter/CompanyTrack/issues/355

**Comment by erikvk** [comment]
How about defining `Headers` as:
```c# public ICollection<(string, string)> Headers { get; private set; }```
Or:
```c# public ICollection<KeyValuePair<string,string>> Headers { get; private set; }```

**Comment by miyconst** [comment]
Closing as won't fix. We are working on .Net Core code host with ASP.NET MVC Core native support, which will provide standard request/response objects.
