### ISSUE TITLE
"Connecting now..." never disappear

### ISSUE THREAD

**Issue by thebrauer** [Starcounter/Home#318]
When I open our application on my phone and lock the screen for approx. 15 minutes and return to the application, it shows an hourglass and "Connecting now..." and the message never disappear even though I can use the application. Sometimes, using the application with "Connecting now..." causes "Connection error" but even then the application still works.

If I return to the application within approx. 10 minutes it seems to connect and the message disappear like it should. 

We are using version RC-2.3.1.7166

**Comment by miyconst** [comment]
cc @warpech, @alshakero, @chrhol

**Comment by alshakero** [comment]
I'm looking at it..

**Comment by alshakero** [comment]
So, this isn't exactly a bug. What is really happening is that when you're using the app with the existence of the top panel and you're kind of overriding the panel by not clicking on it. And the app "seems" to work because you're using HTTP (not WebSocket); each click is an HTTP request. In other words, the app looks like it's working, but it isn't really connected.

To fix this we can:

- Show a semi-opaque overlay beneath the reconnection panel to prevent using the app unless you reconnect.
- Consider successful HTTP requests (that come after failed ones) a trigger for socket reconnection.

**Comment by mmnosek** [comment]
I think that as in https://github.com/Palindrom/Palindrom/issues/184, we should consider that app works if any transportation layer allows completing requests, doesn't matter if it's `http` or `websocket` or something else (in the future). Additionally, `ws` reconnection should be tried as @alshakero proposed. It would solve this problem.

**Comment by warpech** [comment]
Closing as tracked in #179
