### ISSUE TITLE
Upgrading Starcounter always installs developer mode

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Home#336]
Upgrading Starcounter version always installs developer mode even if the original installation was in production mode.

**Comment by ubbeK** [comment]
We are interested in the specific scenario when a Starcounter version is already installed, and another installer is executed (if same installer as the current installed one is used, then it will only uninstall). In this scenario, the installer will first uninstall, and then install again i.e. upgrade/downgrade

There are two separate ways:

1. Commandline
2. GUI

------
### Commandline
* `Starcounter-RC-2.3.1.X-Setup.exe Silent productionmode unattened` should uninstall normally, and then upgrade/downgrade with productionmode, all silently

* `Starcounter-RC-2.3.1.X-Setup.exe Silent unattened` should uninstall normally, and then upgrade/downgrade with developermode (i.e. default values), all silently

### GUI
@miyconst How do we want this? Do we want the GUI to give you the choice to choose upgrade/downgrade mode (i.e. porductionmode or developermode) or should we somehow look at the Starcounter service in order to calculate what mode the previous version was installed on?

**Comment by miyconst** [comment]
Ideally it would be good to automatically detect current installation mode and upgrade/downgrade using the same mode.

Otherwise asking user to select is fine.

**Comment by ubbeK** [comment]
@iqbalskd What is the status of this issue?

**Comment by ubbeK** [comment]
> @iqbalskd What is the status of this issue?
Found the PR: https://github.com/Starcounter/level1/pull/4426

**Comment by iqbalskd** [comment]
Tested and merged.

**Comment by miyconst** [comment]
Now the installation fails with the following exception:

![image](https://user-images.githubusercontent.com/6435556/34555389-d7a70b28-f131-11e7-9752-8c6e2b4dfd79.png)

**Comment by miyconst** [comment]
```
Starcounter-RC-2.3.1.8264-Setup.exe (Jan 4, 2018 1:01:26 AM)
```

**Comment by miyconst** [comment]
Clarification:

- It fails when installing developer mode.
- It fails when upgrading developer mode.
- Production mode was not checked.

**Comment by ubbeK** [comment]
I cannot reproduce this error. Tested all kind of combinations of
* install / uninstall / upgrade 
* Production Mode / Developer Mode without Extension / Developer Mode without Extension

I used
* `Starcounter-RC-2.3.1.8199-Setup.exe`
* `Starcounter-RC-2.3.1.8264-Setup.exe`

-----

> It fails when upgrading developer mode.

What Starcounter version did you use when upgrading? cc @miyconst

**Comment by miyconst** [comment]
>What Starcounter version did you use when upgrading? cc @miyconst

I can't check that right now because it was removed during the upgrade, still the fresh installation fails. Trying without the documents folder.

**Comment by ubbeK** [comment]
tested all that through GUI and through CLI with arguments

**Comment by ubbeK** [comment]
The only thing I can find is when downgrading to `Starcounter-RC-2.3.1.8199-Setup.exe` from `Starcounter-RC-2.3.1.8264-Setup.exe` which shuts down the installer silently. cc @iqbalskd

**Comment by miyconst** [comment]
>I cannot reproduce this error. Tested all kind of combinations of

That's bad, but I can't reproduce it any more. It was failing with the exception above multiple times. Then I:

- Dropped Starcounter documents folder.
- Installed Starcounter.
- Uninstalled Starcounter.
- Replaced the new documents folder with the old one.
- Trying again - works.

@ubbeK thanks for checking, I ask Anna from Heads to check, and if it works for her, we close the issue.

**Comment by Mihaiii** [comment]
I had the same problem when downgrading from 2.4 to 2.3. It was annoying for me, but this isn't something that any SC customer/client would do afaik so I can live with it if it happens again.

**Comment by miyconst** [comment]
@Mihaiii thank you for the hint, it could actually be the case for me as well. Still, I ask you to report such issues when they happen.

**Comment by miyconst** [comment]
The fix is confirmed by Heads.
