### ISSUE TITLE
Find the way to make 2.3/2.4 projects compatible, otherwise provide support suppressing warnings

### ISSUE THREAD

**Issue by kegor** [Starcounter/Home#353]
Initially this issue starts in [Blending/Solution builds with warnings#41](https://github.com/Starcounter/Blending/issues/41), and looks like this:
![image](https://user-images.githubusercontent.com/17431807/34987711-38471c44-facd-11e7-93df-e636e3b61598.png)

@per-samuelsson already gave his opinion in the issue mentioned above and additionally suggested to consider possibility to find solution for this issue in separate work-item.

**Comment by per-samuelsson** [comment]
@miyconst, can you (possibly with advice from relevant teams) prioritize this eventually, so I know how I need to schedule. I'll need to interrupt new weaver development if I'm assigned to do this. Which is fine o/c, depending on urgency. Just want to make it clear.

**Comment by miyconst** [comment]
@per-samuelsson please fix this during the next week.

**Comment by per-samuelsson** [comment]
> @per-samuelsson please fix this during the next week.

OK, got it. Will do. Not sure I can just "fix" it, as I'm not sure of any solution right now, but lets see. I'll give it some love at least.

**Comment by un-tone** [comment]
I have an idea how we could maintain 2 versions of NuGet packages.

For SC 2.4 we can publish packages with a pre-release flag (beta, alpha). 
So using this approach, we will publish our libraries which supports v2.3 in the release NuGet channel and libraries which supports v2.4 in the pre-release channel.

@per-samuelsson @warpech @miyconst WDYT?

**Comment by k-rus** [comment]
> For SC 2.4 we can publish packages with a pre-release flag (beta, alpha).
> So using this approach, we will publish our libraries which supports v2.3 in the release NuGet channel and libraries which supports v2.4 in the pre-release channel.

In general it is not good enough for us, since it allows to have only two versions of packages, if I understood correctly. We need to be more flexible. But it can be good enough for the beginning. 2.4 is Alpha.

**Comment by miyconst** [comment]
>For SC 2.4 we can publish packages with a pre-release flag (beta, alpha).

Any package with a suffix is less than a package without suffix. This means that `1.0.0` is greater than `1.0.0-alpha`. So, in the very end we still have to split packages for `2.3.1` and `2.4` with the version number.

Adding a suffix to the package should indicate the package state, and it's a good idea regardless of Starcounter version it's designed for.

**Comment by per-samuelsson** [comment]
> @per-samuelsson WDYT?

As long as we need distinct builds depending on targeted Starcounter version, the proposed approach is the expected and recommended one.

Imagine we would ship 2.3.1 and 2.4 of Starcounter as NuGet packages, and adhered to semantic versioning. The 2.4 package would certainly be versioned a pre-release package itself. Hence, applications built on top of it should be considered pre-release too.

**Comment by per-samuelsson** [comment]
An addition to the above, making it even clearer: if you are strict, you **can't** release any app targeting 2.4 as *anything other than* a pre-release (with proper such semantic version). Simply because it depends on a version of Starcounter not yet released.

Yes, I here you come back with the argument that "well, a large portion of our developers already use 2.4". Sure, that's fine. But it's still not released. And hence should be considered pre-release.

**Comment by per-samuelsson** [comment]
To be frank, I think it's really important all app-teams start to fully embrace the fact that apps should be targeting different versions of Starcounter, and set up *every* repository that way. Yes, our aim since some time back is trying to be backwards compatible as far as possible (at least API-wise) in all future releases. But it's still unlikely that applications won't need to change.

At some point after 2.4, we'll see Nova, and there will certainly be some staging period when all apps will start to target that, and *still have to be released*. It will pose a scenario quite similar to the one we face right now. Branching- and versioning-strategies across all apps should expect such as something normal.

**Comment by miyconst** [comment]
On the last release planning it was decided to don't do anything regarding this feature. Instead focus on the shift to Starcounter Nova and the new features.
