### ISSUE TITLE
Import HTML composition not working

### ISSUE THREAD

**Issue by papusa** [Starcounter/Home#61]
### Description

When I use GUI to save my HTML composition, it saves my HTML to the database with key "/sc/htmlmerger?RoomManagement=/EditRoomPage.html&Images=/Images/viewmodels/MasterPage.html". Also, I've been trying to use I would like to use REST API for importing. However it doesn't work: 
I used URI "http://localhost:8080/sc/partial/composition?key=/sc/htmlmerger?RoomManagement=/EditRoomPage.html&Images=/Images/viewmodels/MasterPage.html" to make POST and GET requests. Both of them return 404.

**Comment by dan31** [comment]
CC @per-samuelsson @warpech @tomalec

**Comment by per-samuelsson** [comment]
cc @miyconst

**Comment by miyconst** [comment]
@warpech, @tomalec, could some of you answer the question please?

**Comment by warpech** [comment]
Sorry, I must have missed it. It seems to be the same problem as https://github.com/Starcounter/level1/issues/3915. 

It will return 404 if CompositionEditor is not running. Is that app running?

**Comment by tomalec** [comment]
@warpech Did you mean CompositionProvider?

**Comment by warpech** [comment]
No, I mean CompositionEditor, because that is the application that calls `Starcounter.HTMLComposition.Register();`: https://github.com/search?utf8=%E2%9C%93&q=%22HTMLComposition.Register%22+user%3AStarcounter+user%3AStarcounterApps+user%3AJuicy+user%3AStarcounter-Jack+user%3APalindrom+user%3ASmorgasbord-Development&type=Code

**Comment by miyconst** [comment]
Archiving.
