### ISSUE TITLE
Visual Studio 2012

### ISSUE THREAD

**Issue by careri** [Starcounter/Home#90]
Hi!

I just moved from a 2.3 built in january to the latest RC, and now I realize that you've removed support for anything less than 2015 Pro. 

Have you changed the implementation of the extension so that it relies on some API in VS2015? 
I had no problem running it in VS2012.

We've been talking about moving to a newer version of VS, but most of us (Heads) are still at 2012. 
Any change of updating the vsixmanifest to support 2012 again?

**Comment by per-samuelsson** [comment]
Hi @careri,

As far as I remember, things are compatible between those versions, but I'm not 100% sure.

We took a decision to officially support only the two latest versions of Visual Studio, because we want to lower the maintenance burden in the area. That means that as of today, we support VS 2015 and 2017. The 2012 version is... well, 5 years old, and 4 versions back, and even 2017 is now considered stable.

Is there any obstacle for you to move to say 2015?

Otherwise, you could of course clone https://github.com/Starcounter/Starcounter.VisualStudio and tweak it for 2012 yourself. I think it's doable. But I bet that's nothing you've dreamt of doing, right? 😃

**Comment by careri** [comment]
Already doing it... 
@hentil is requesting a budget to upgrade our VS. But nothing is happening

These are the obstacles, that I'm overcoming:
 
1. 4.6 first in the path, so that the correct msbuild.exe is used
2. SET MSBUILDTREATALLTOOLSVERSIONSASCURRENT=true
3. Install Microsoft.Net.Compilers for all projects:
  Install-Package Microsoft.Net.Compilers i alla projekt som ska använda .Net46
4. Install Visual C++ Build Tools
  
So soon I'll probably have that vsix...

**Comment by careri** [comment]
Argh, almost... I need the installer for VS2015 to install the Visual Studio SDK. Damnit!

Looks like I'll get my hands on a newer VS soon

**Comment by careri** [comment]
Eh, doh. I managed to build:
https://github.com/Starcounter/level1

But now I realize that the visual studio in that project isn't the one you linked to. 
Fixing that VSIX was far simpler!

FYI I just changed the manifest to support 2012, works like before

**Comment by per-samuelsson** [comment]
> Fixing that VSIX was far simpler!

Well, they brought in hefty changes to extension stuff in 2017, and hence we had to rework it to support that. At the same time we decided to move the extension out of Level1 and into https://github.com/Starcounter/Starcounter.VisualStudio.

**Comment by miyconst** [comment]
Archiving the issue.
